// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKV_7IoAwktMO97A_irb9XEGGh3qEbcZ4',
    appId: '1:952580895930:web:5a97c8809ff2266fc47e83',
    messagingSenderId: '952580895930',
    projectId: 'newsly-f0476',
    authDomain: 'newsly-f0476.firebaseapp.com',
    storageBucket: 'newsly-f0476.firebasestorage.app',
    measurementId: 'G-26G535EZ5W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAOEdAfd0lRjkxct6ezg-rspAKjl_4vo4',
    appId: '1:952580895930:android:644bc419e0e4f006c47e83',
    messagingSenderId: '952580895930',
    projectId: 'newsly-f0476',
    storageBucket: 'newsly-f0476.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJR8mHWZ14JHONfeY3odo05AWDRohQRng',
    appId: '1:952580895930:ios:a89bde3a90849abbc47e83',
    messagingSenderId: '952580895930',
    projectId: 'newsly-f0476',
    storageBucket: 'newsly-f0476.firebasestorage.app',
    iosClientId: '952580895930-l7iffmmphk52ebm2tkle4tjf9bm4maor.apps.googleusercontent.com',
    iosBundleId: 'com.example.newsly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJR8mHWZ14JHONfeY3odo05AWDRohQRng',
    appId: '1:952580895930:ios:a89bde3a90849abbc47e83',
    messagingSenderId: '952580895930',
    projectId: 'newsly-f0476',
    storageBucket: 'newsly-f0476.firebasestorage.app',
    iosClientId: '952580895930-l7iffmmphk52ebm2tkle4tjf9bm4maor.apps.googleusercontent.com',
    iosBundleId: 'com.example.newsly',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKV_7IoAwktMO97A_irb9XEGGh3qEbcZ4',
    appId: '1:952580895930:web:518c1ca0ae8a5761c47e83',
    messagingSenderId: '952580895930',
    projectId: 'newsly-f0476',
    authDomain: 'newsly-f0476.firebaseapp.com',
    storageBucket: 'newsly-f0476.firebasestorage.app',
    measurementId: 'G-YZG3FXH8QN',
  );
}
